<?php
define('ROOT_PATH',dirname(__DIR__).DIRECTORY_SEPARATOR);require ROOT_PATH.'classes/template/smarty.class.php';
$s=new Smarty();$s->setTemplateDir(ROOT_PATH.'templates');$s->setCompileDir(sys_get_temp_dir());
$r=['mode'=>'hours','filters'=>['from'=>'2026-10-01','to'=>'2026-10-02','project_id'=>null,'user_id'=>null],'data'=>['summary'=>['hours'=>'2.00','regular_hours'=>'2.00','ot_hours'=>'0.00'],'rows'=>[['work_date'=>'2026-10-01','shift_label'=>'Day','user_name'=>'<script>bad</script>','project_name'=>'Project','task_name'=>'Task','hours'=>'2.00','regular_hours'=>'2.00','ot_hours'=>'0.00','description'=>'<img src=x>','historical'=>1]],'by_user'=>[],'page'=>1,'total_pages'=>2]];
$r['filters']['mode']='hours';$r['data']['by_user']=[['user_name'=>'Sample','hours'=>'2.00','regular_hours'=>'2.00','ot_hours'=>'0.00']];
$s->assign(['pageTitle'=>'Reports','report'=>$r,'error'=>'','csrfToken'=>'test','canExportReports'=>true,'canReportCosts'=>false]);$html=$s->fetch('admin/pm-reports.tpl.html');
foreach(['&lt;script&gt;','value="export"','name="op" value="pmreports"','page=2','(lịch sử)'] as $n)if(!str_contains($html,$n))throw new RuntimeException('Missing report view: '.$n);
if(str_contains($html,'<script>bad')||str_contains($html,'<img src=x>'))throw new RuntimeException('Report escaping failed.');
if(!preg_match('/<header class="pm-report-header">.*?value="export".*?<\/header>/s',$html)||!str_contains($html,'class="pm-report-summary"'))throw new RuntimeException('Export header/summary missing.');
$preview=in_array('--preview',$argv,true);if($preview)file_put_contents(ROOT_PATH.'.local/phase9b-reports-hours.html',str_replace('<head>','<head><base href="/">',$html));
$s->assign('canExportReports',false);$html=$s->fetch('admin/pm-reports.tpl.html');if(str_contains($html,'value="export"'))throw new RuntimeException('Export denied but rendered.');if($preview)file_put_contents(ROOT_PATH.'.local/phase9b-reports-restricted.html',str_replace('<head>','<head><base href="/">',$html));
$r['mode']='costs';$r['filters']['mode']='costs';$r['data']=['valuation_date'=>'2026-10-06','warnings'=>['<script>mixed currency</script>'],'projects'=>[['name'=>'Sample','budget'=>'1234567890123.45','actual'=>['cost'=>null,'currency'=>null],'lifetime'=>['cost'=>'100.00','currency'=>'VND'],'estimate'=>['cost'=>null,'currency'=>null]]],'page'=>1,'total_pages'=>1];$s->assign(['report'=>$r,'canReportCosts'=>true,'canExportReports'=>true]);$html=$s->fetch('admin/pm-reports.tpl.html');
if(str_contains($html,'<script>mixed')||!str_contains($html,'1234567890123.45')||str_contains($html,'class="pm-report-summary"'))throw new RuntimeException('Cost report exact/empty/escaping failed.');if($preview)file_put_contents(ROOT_PATH.'.local/phase9b-reports-costs.html',str_replace('<head>','<head><base href="/">',$html));
$s->assign(['report'=>null,'error'=>'<script>bad</script>']);$html=$s->fetch('admin/pm-reports.tpl.html');if(str_contains($html,'<script>bad'))throw new RuntimeException('Report error escaping failed.');
if(str_contains($html,'value="export"'))throw new RuntimeException('Missing report exposes export.');if($preview)file_put_contents(ROOT_PATH.'.local/phase9b-reports-error.html',str_replace('<head>','<head><base href="/">',$html));
echo "PASS: reports Smarty, escaping, filters/pagination, export route and CSRF fields.\n";
