<?php
include_once(ROOT_PATH.'classes/database/model.class.php');
class EditorialUserLibrary extends Model {
    var $table; var $_db; var $store_id;
    function __construct($store_id=1,$database='') { global $db; $this->_db=$database?$database:$db; $this->table=DB_PREFIX.'editorial_user_library'; $this->store_id=(int)$store_id; }
    function allowedType($type) { return in_array($type,array('saved','history','watch_later'),true); }
    function getItems($customerId,$type='',$limit=100) { $customerId=(int)$customerId; $limit=max(1,min(200,(int)$limit)); $condition="`store_id`=".$this->store_id." AND `customer_id`=".$customerId; if($type&&$this->allowedType($type))$condition.=" AND `item_type`='".addslashes($type)."'"; $rows=$this->select('*',$condition,array('activity_at'=>'DESC'),0,$limit); return $rows?$rows:array(); }
    function getItem($customerId,$type,$key) { $customerId=(int)$customerId; $key=trim((string)$key); if(!$customerId||!$this->allowedType($type)||$key===''||strlen($key)>191)return 0; $condition="`store_id`=".$this->store_id." AND `customer_id`=".$customerId." AND `item_type`='".addslashes($type)."' AND `item_key`='".addslashes($key)."'"; $rows=$this->select('*',$condition,array(),0,1); return $rows?$rows[0]:0; }
    function saveItem($customerId,$type,$key,$payload,$progress=0) { $customerId=(int)$customerId; $key=trim((string)$key); if(!$customerId||!$this->allowedType($type)||$key===''||strlen($key)>191)return 0; $progress=max(0,min(100,(int)$progress)); $condition="`store_id`=".$this->store_id." AND `customer_id`=".$customerId." AND `item_type`='".addslashes($type)."' AND `item_key`='".addslashes($key)."'"; $existing=$this->select('id,progress',$condition,array(),0,1); if($existing&&$type==='history')$progress=max($progress,(int)$existing[0]['progress']); $now=date('Y-m-d H:i:s'); $fields=array('payload'=>$payload,'progress'=>$progress,'activity_at'=>$now,'date_updated'=>$now); if($existing)return $this->update($fields,"`id`=".(int)$existing[0]['id']); $fields+=array('store_id'=>$this->store_id,'customer_id'=>$customerId,'item_type'=>$type,'item_key'=>$key,'date_created'=>$now); return $this->add($fields); }
    function removeItem($customerId,$type,$key) { if(!$this->allowedType($type))return 0; return $this->delete("`store_id`=".$this->store_id." AND `customer_id`=".(int)$customerId." AND `item_type`='".addslashes($type)."' AND `item_key`='".addslashes($key)."'"); }
}
